# Configuraci\u00f3n del servidor
server.port=8080

# Nombre de la aplicaci\u00f3n
spring.application.name=liberafrutas

# Para evitar cach\u00e9 de archivos est\u00e1ticos (recomendado para desarrollo)
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# Configuraci\u00f3n para servir archivos est\u00e1ticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**